In [25]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://postgres:123456789@localhost:5432/retail_sales_db")

In [26]:
query_data = "SELECT * FROM orders;"
data = pd.read_sql_query(query_data, engine)
data.head(3)

,order_id,order_date,customer_id,store_id,product_id,quantity,unit_price,discount,cost
0,ID-2023-00077,2023-01-01,CUST-019,ST-001,PRD-015,1.0,400000.0,0.0,303000.0
1,ID-2023-01389,2023-01-01,CUST-086,ST-005,PRD-004,1.0,2395000.0,0.0,1726000.0
2,ID-2023-00556,2023-01-03,CUST-002,ST-003,PRD-016,1.0,302000.0,0.0,222000.0

In [27]:
query_analisis = """
    SELECT 
        s.order_id,
        s.order_date,
        s.store_id,
        st.region,
        s.customer_id,
        c.segment,
        s.product_id,
        p.product_name,
        p.category,
        s.quantity,
        s.unit_price,
        s.discount,
        s.cost
    FROM orders s
    LEFT JOIN customer c
    ON c.customer_id=s.customer_id
    LEFT JOIN product p
    ON p.product_id=s.product_id
    LEFT JOIN store st
    ON st.store_id=s.store_id
    ORDER BY s.order_date;
"""

df = pd.read_sql_query(query_analisis, engine)
df

,order_id,order_date,store_id,region,customer_id,segment,product_id,product_name,category,quantity,unit_price,discount,cost
0,ID-2023-00077,2023-01-01,ST-001,Jawa,CUST-019,Corporate,PRD-015,Blender Miyako 3 in 1,home appliances,1.0,400000.0,0.00,303000.0
1,ID-2023-01389,2023-01-01,ST-005,bali & nusa tenggara,CUST-086,Consumer,PRD-004,Smart TV Aqua 32 Inch,ELECTRONICS,1.0,2395000.0,0.00,1726000.0
2,ID-2023-00556,2023-01-03,ST-003,kalimantan,CUST-002,,PRD-016,Kipas Angin Maspion,home appliances,1.0,302000.0,0.00,222000.0
3,ID-2023-00851,2023-01-03,ST-002,Sumatera,CUST-108,Home Office,PRD-026,Sepatu Lari Mills,Sports,1.0,322000.0,0.00,229000.0
4,ID-2023-00851,2023-01-03,ST-002,Sumatera,CUST-108,Home Office,PRD-026,Sepatu Lari Mills,Sports,1.0,322000.0,0.00,229000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2869,ID-2026-00857,2026-06-29,ST-001,Jawa,CUST-013,CONSUMER,PRD-025,Raket Badminton Specs,Sports,1.0,599000.0,0.05,416000.0
2870,ID-2026-00237,2026-06-30,ST-002,Sumatera,CUST-029,Corporate,PRD-025,Raket Badminton Specs,Sports,1.0,430000.0,0.00,294000.0
2871,ID-2026-00237,2026-06-30,ST-002,Sumatera,CUST-029,Corporate,PRD-024,Matras Yoga Speeds,Sports,1.0,163000.0,0.00,109000.0
2872,ID-2026-00237,2026-06-30,ST-002,Sumatera,CUST-029,Corporate,PRD-007,Sofa Minimalis Jepara,Furniture,1.0,5032000.0,0.00,3890000.0
2873,ID-2026-01682,2026-06-30,ST-002,Sumatera,CUST-001,Consumer,PRD-025,Raket Badminton Specs,Sports,1.0,517000.0,0.00,358000.0

In [28]:
df.to_csv('data.csv')

In [29]:
# Tutup koneksi jika sudah selesai
engine.dispose()